version : '3'

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    depends_on :
      - wordpress
    restart: always
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wp_volume:/var/www/

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    depends_on :
      - mariadb
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - wp_volume:/var/www/

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql/

networks:
  inception_network:
    driver: bridge

volumes:
    db_volume:
      driver_opts:
        type: volume
        o : 'bind'
        device: '/home/ycha/data/database'

    wp_volume:
      driver_opts:
        type: volume
        o : 'bind'
        device: '/home/ycha/data/wordpress'
